### ISSUE TITLE
Processing of huge data sets

### ISSUE THREAD

**Issue by Mr-Question** [rballester/tthresh#2]
Hello!

Is there a possibility to reduce amount of allocated memory occupied by auxiliary data structures during compression/decompression, e.g. by separating of input data on subsets, e.g. hundred of slices, and processing entire dataset part by part?

What side-effects could appear using such approach?

Best regards.

**Comment by rballester** [comment]
This would definitely help with massive data sets. It is not currently supported by the package, though --you'll need to split (before compression) and reassemble togethre (after decompression) those parts yourself.

I don't foresee any special side-effect, except losing some compression power, especially if the subparts are very small. Just as a note of advice, try to use as-cubic-as-possible bricks, since the Tucker format is not good for 1D or 2D data compression (i.e. don't try to compress slices of thickness 1 of a 3D volume!).

**Comment by Mr-Question** [comment]
Great, I will give it a try. Thanks a lot for the feedback!
